version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: dt_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dt_user
      POSTGRES_PASSWORD: dt_pass
      POSTGRES_DB: dt_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: dt_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dt_app
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://dt_user:dt_pass@postgres:5432/dt_db
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
    ports:
      - "3003:3003"
    command: >
      sh -c "
        npm run migration:run &&
        npm run start
      "

volumes:
  pgdata:
